### ==> AUTH
### AUTHENTICATION
POST http://localhost:8080/api/v1/auth
Content-Type: application/json

{
    "username":"layhome12",
    "password":"@#Password123"
}

### REFRESH TOKEN
GET http://localhost:8080/api/v1/refresh-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjc1Nzg2MDIwLCJleHAiOjE2NzgzNzgwMjB9.ihNp0vDs_gT5pOhhgsqrrPFtu3Iq_BYvo7QX2PC5XxA

### ==> USERS
### GET
GET http://localhost:8080/api/v1/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjc4NzIzMTUwLCJleHAiOjE2Nzg4MDk1NTB9.__JzmGaYoB8eTaaRmcAniddnqq4ZquKcWDUF8gDKAKA

### SHOW
GET http://localhost:8080/api/v1/user/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjc4NzIzMTUwLCJleHAiOjE2Nzg4MDk1NTB9.__JzmGaYoB8eTaaRmcAniddnqq4ZquKcWDUF8gDKAKA

### STORE
POST http://localhost:8080/api/v1/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjc4NzIzMTUwLCJleHAiOjE2Nzg4MDk1NTB9.__JzmGaYoB8eTaaRmcAniddnqq4ZquKcWDUF8gDKAKA
Content-Type: application/json

{
    "username":"layhome12",
    "password":"@#Password123",
    "user_email":"layhome12@gmail.com",
    "user_nama":"Layhome"
}
### UPDATE
PUT http://localhost:8080/api/v1/user/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjc4NzIzMTUwLCJleHAiOjE2Nzg4MDk1NTB9.__JzmGaYoB8eTaaRmcAniddnqq4ZquKcWDUF8gDKAKA
Content-Type: application/json

{
    "username":"layhome12",
    "password":"@#Password124",
    "user_email":"layhome12@gmail.com",
    "user_nama":"Layhome uWu"
}
### DELETE
DELETE http://localhost:8080/api/v1/user/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjc4NzIzMTUwLCJleHAiOjE2Nzg4MDk1NTB9.__JzmGaYoB8eTaaRmcAniddnqq4ZquKcWDUF8gDKAKA